# This file relates to internal XMOS infrastructure and should be ignored by users

project: 'ai-tools'
title: 'AI tools documentation'
version: 1.0.0

documentation:
  exclude_patterns_path: exclude-patterns.inc
  root_doc: rst/index.rst
  latex_toc_depth: 1
  cognidox_part_number: XM-015210-UG
  pdfs:
    rst/index.rst:
      pdf_title: '{{title}}'
      pdf_filename: 'ai_tools_v{{version}}'

