# The TARGET variable determines what target system the application is 
# compiled for. It either refers to an XN file in the source directories
# or a valid argument for the --target option when compiling.

TARGET = XU316-1024-QF60-C20.xn

# The APP_NAME variable determines the name of the final .xe file. It should
# not include the .xe postfix. If left blank the name will default to 
# the project name
APP_NAME = test_model

ALL_CONFIGS = xs3
CONFIG = xs3

# The flags passed to xcc when building the application
# You can also set the following to override flags for a particular language:
#
#    XCC_XC_FLAGS, XCC_C_FLAGS, XCC_ASM_FLAGS, XCC_CPP_FLAGS
#
# If the variable XCC_MAP_FLAGS is set it overrides the flags passed to 
# xcc for the final link (mapping) stage.

XCC_FLAGS = -Wall -Os -g -report
XCC_FLAGS += -Wcpp,-std=c++11
XCC_FLAGS += -DTF_LITE_STATIC_MEMORY
XCC_FLAGS += -DTF_LITE_DISABLE_X86_NEON
XCC_FLAGS += -DNDEBUG
XCC_FLAGS += -mcmodel=large
#XCC_FLAGS += -DXCORE
XCC_FLAGS += -Wno-unknown-attributes
XCC_FLAGS += -Wno-xcore-fptrgroup
XCC_FLAGS += -Wno-xcore-fptrgroup
XCC_FLAGS += -fcmdline-buffer-bytes=256

# The USED_MODULES variable lists other module used by the application. 
#USED_MODULES = 

#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
