# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

class AssociatedFileType(object):
    UNKNOWN = 0
    DESCRIPTIONS = 1
    LABELS = 2
    VOCABULARY = 3
    LOCALIZATION = 4

