# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

class ColorSpaceType(object):
    UNKNOWN = 0
    RGB = 1
    BGR = 2
    YUV = 3
    HSV = 4
    GRAYSCALE = 5

