# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

class ContentType(object):
    UNKNOWN = 0
    IMAGE = 1
    VIDEO = 2
    TEXT = 3
    AUDIO = 4
    FEATURE = 5

