set(XMOS_AITOOLSLIB_DEFINITIONS
        "TF_LITE_STATIC_MEMORY"
		"TF_LITE_STRIP_ERROR_STRINGS"
		"XCORE"
		"NO_INTERPRETER"
    )

if(NOT ${CMAKE_SYSTEM_PROCESSOR} STREQUAL XCORE_XS3A)
	set(XMOS_AITOOLSLIB_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/../lib/libhost_xtflitemicro.a")
else()
	set(XMOS_AITOOLSLIB_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/../lib/libxtflitemicro.a")
endif()
set(XMOS_AITOOLSLIB_INCLUDES "${CMAKE_CURRENT_LIST_DIR}/../include")
