# Copyright (c) 2020, XMOS Ltd, All rights reserved

# type: ignore

from enum import Enum

from . import schema_py_generated as schema, BuiltinOpCodes

BuiltinOptions = Enum(
    "BuiltinOptions",
    {k: v for k, v in vars(schema.BuiltinOptions).items() if not k.startswith("__")},
)

# this mapping should follow the schema and:
# tensorflow/tensorflow/lite/core/api/flatbuffer_conversions.cc
__BuiltinOptions_from_BuiltinOpCodes = {
    BuiltinOpCodes.ADD: BuiltinOptions.AddOptions,
    BuiltinOpCodes.AVERAGE_POOL_2D: BuiltinOptions.Pool2DOptions,
    BuiltinOpCodes.CONCATENATION: BuiltinOptions.ConcatenationOptions,
    BuiltinOpCodes.CONV_2D: BuiltinOptions.Conv2DOptions,
    BuiltinOpCodes.DEPTHWISE_CONV_2D: BuiltinOptions.DepthwiseConv2DOptions,
    BuiltinOpCodes.DEPTH_TO_SPACE: BuiltinOptions.DepthToSpaceOptions,
    BuiltinOpCodes.DEQUANTIZE: BuiltinOptions.DequantizeOptions,
    BuiltinOpCodes.EMBEDDING_LOOKUP: BuiltinOptions.NONE,
    BuiltinOpCodes.FLOOR: BuiltinOptions.NONE,
    BuiltinOpCodes.FULLY_CONNECTED: BuiltinOptions.FullyConnectedOptions,
    BuiltinOpCodes.HASHTABLE_LOOKUP: BuiltinOptions.NONE,
    BuiltinOpCodes.L2_NORMALIZATION: BuiltinOptions.L2NormOptions,
    BuiltinOpCodes.L2_POOL_2D: BuiltinOptions.Pool2DOptions,
    BuiltinOpCodes.LOCAL_RESPONSE_NORMALIZATION: BuiltinOptions.LocalResponseNormalizationOptions,
    BuiltinOpCodes.LOGISTIC: BuiltinOptions.NONE,
    BuiltinOpCodes.LSH_PROJECTION: BuiltinOptions.LSHProjectionOptions,
    BuiltinOpCodes.LSTM: BuiltinOptions.LSTMOptions,
    BuiltinOpCodes.MAX_POOL_2D: BuiltinOptions.Pool2DOptions,
    BuiltinOpCodes.MUL: BuiltinOptions.MulOptions,
    BuiltinOpCodes.RELU: BuiltinOptions.NONE,
    BuiltinOpCodes.RELU_N1_TO_1: BuiltinOptions.NONE,
    BuiltinOpCodes.RELU6: BuiltinOptions.NONE,
    BuiltinOpCodes.RESHAPE: BuiltinOptions.ReshapeOptions,
    BuiltinOpCodes.RESIZE_BILINEAR: BuiltinOptions.ResizeBilinearOptions,
    BuiltinOpCodes.RNN: BuiltinOptions.RNNOptions,
    BuiltinOpCodes.SOFTMAX: BuiltinOptions.SoftmaxOptions,
    BuiltinOpCodes.SPACE_TO_DEPTH: BuiltinOptions.SpaceToDepthOptions,
    BuiltinOpCodes.SVDF: BuiltinOptions.SVDFOptions,
    BuiltinOpCodes.TANH: BuiltinOptions.NONE,
    BuiltinOpCodes.CONCAT_EMBEDDINGS: BuiltinOptions.ConcatEmbeddingsOptions,
    BuiltinOpCodes.SKIP_GRAM: BuiltinOptions.SkipGramOptions,
    BuiltinOpCodes.CALL: BuiltinOptions.CallOptions,
    BuiltinOpCodes.CUSTOM: BuiltinOptions.NONE,
    BuiltinOpCodes.EMBEDDING_LOOKUP_SPARSE: BuiltinOptions.EmbeddingLookupSparseOptions,
    BuiltinOpCodes.PAD: BuiltinOptions.PadOptions,
    BuiltinOpCodes.UNIDIRECTIONAL_SEQUENCE_RNN: BuiltinOptions.SequenceRNNOptions,
    BuiltinOpCodes.GATHER: BuiltinOptions.GatherOptions,
    BuiltinOpCodes.BATCH_TO_SPACE_ND: BuiltinOptions.BatchToSpaceNDOptions,
    BuiltinOpCodes.SPACE_TO_BATCH_ND: BuiltinOptions.SpaceToBatchNDOptions,
    BuiltinOpCodes.TRANSPOSE: BuiltinOptions.TransposeOptions,
    BuiltinOpCodes.MEAN: BuiltinOptions.ReducerOptions,
    BuiltinOpCodes.SUB: BuiltinOptions.SubOptions,
    BuiltinOpCodes.DIV: BuiltinOptions.DivOptions,
    BuiltinOpCodes.SQUEEZE: BuiltinOptions.SqueezeOptions,
    BuiltinOpCodes.UNIDIRECTIONAL_SEQUENCE_LSTM: BuiltinOptions.UnidirectionalSequenceLSTMOptions,
    BuiltinOpCodes.STRIDED_SLICE: BuiltinOptions.StridedSliceOptions,
    BuiltinOpCodes.BIDIRECTIONAL_SEQUENCE_RNN: BuiltinOptions.BidirectionalSequenceRNNOptions,
    BuiltinOpCodes.EXP: BuiltinOptions.ExpOptions,
    BuiltinOpCodes.TOPK_V2: BuiltinOptions.TopKV2Options,
    BuiltinOpCodes.SPLIT: BuiltinOptions.SplitOptions,
    BuiltinOpCodes.LOG_SOFTMAX: BuiltinOptions.LogSoftmaxOptions,
    BuiltinOpCodes.DELEGATE: BuiltinOptions.NONE,
    BuiltinOpCodes.BIDIRECTIONAL_SEQUENCE_LSTM: BuiltinOptions.BidirectionalSequenceLSTMOptions,
    BuiltinOpCodes.CAST: BuiltinOptions.CastOptions,
    BuiltinOpCodes.PRELU: BuiltinOptions.NONE,
    BuiltinOpCodes.MAXIMUM: BuiltinOptions.MaximumMinimumOptions,
    BuiltinOpCodes.ARG_MAX: BuiltinOptions.ArgMaxOptions,
    BuiltinOpCodes.MINIMUM: BuiltinOptions.MaximumMinimumOptions,
    BuiltinOpCodes.LESS: BuiltinOptions.LessOptions,
    BuiltinOpCodes.NEG: BuiltinOptions.NegOptions,
    BuiltinOpCodes.PADV2: BuiltinOptions.PadV2Options,
    BuiltinOpCodes.GREATER: BuiltinOptions.GreaterOptions,
    BuiltinOpCodes.GREATER_EQUAL: BuiltinOptions.GreaterEqualOptions,
    BuiltinOpCodes.LESS_EQUAL: BuiltinOptions.LessEqualOptions,
    BuiltinOpCodes.SELECT: BuiltinOptions.SelectOptions,
    BuiltinOpCodes.SLICE: BuiltinOptions.SliceOptions,
    BuiltinOpCodes.SIN: BuiltinOptions.NONE,
    BuiltinOpCodes.TRANSPOSE_CONV: BuiltinOptions.TransposeConvOptions,
    BuiltinOpCodes.SPARSE_TO_DENSE: BuiltinOptions.SparseToDenseOptions,
    BuiltinOpCodes.TILE: BuiltinOptions.TileOptions,
    BuiltinOpCodes.EXPAND_DIMS: BuiltinOptions.ExpandDimsOptions,
    BuiltinOpCodes.EQUAL: BuiltinOptions.EqualOptions,
    BuiltinOpCodes.NOT_EQUAL: BuiltinOptions.NotEqualOptions,
    BuiltinOpCodes.LOG: BuiltinOptions.NONE,
    BuiltinOpCodes.SUM: BuiltinOptions.ReducerOptions,
    BuiltinOpCodes.SQRT: BuiltinOptions.NONE,
    BuiltinOpCodes.RSQRT: BuiltinOptions.NONE,
    BuiltinOpCodes.SHAPE: BuiltinOptions.ShapeOptions,
    BuiltinOpCodes.POW: BuiltinOptions.PowOptions,
    BuiltinOpCodes.ARG_MIN: BuiltinOptions.ArgMinOptions,
    BuiltinOpCodes.FAKE_QUANT: BuiltinOptions.FakeQuantOptions,
    BuiltinOpCodes.REDUCE_PROD: BuiltinOptions.ReducerOptions,
    BuiltinOpCodes.REDUCE_MAX: BuiltinOptions.ReducerOptions,
    BuiltinOpCodes.PACK: BuiltinOptions.PackOptions,
    BuiltinOpCodes.LOGICAL_OR: BuiltinOptions.LogicalOrOptions,
    BuiltinOpCodes.ONE_HOT: BuiltinOptions.OneHotOptions,
    BuiltinOpCodes.LOGICAL_AND: BuiltinOptions.LogicalAndOptions,
    BuiltinOpCodes.LOGICAL_NOT: BuiltinOptions.LogicalNotOptions,
    BuiltinOpCodes.UNPACK: BuiltinOptions.UnpackOptions,
    BuiltinOpCodes.REDUCE_MIN: BuiltinOptions.ReducerOptions,
    BuiltinOpCodes.FLOOR_DIV: BuiltinOptions.FloorDivOptions,
    BuiltinOpCodes.REDUCE_ANY: BuiltinOptions.ReducerOptions,
    BuiltinOpCodes.SQUARE: BuiltinOptions.SquareOptions,
    BuiltinOpCodes.ZEROS_LIKE: BuiltinOptions.ZerosLikeOptions,
    BuiltinOpCodes.FILL: BuiltinOptions.FillOptions,
    BuiltinOpCodes.FLOOR_MOD: BuiltinOptions.FloorModOptions,
    BuiltinOpCodes.RANGE: BuiltinOptions.RangeOptions,
    BuiltinOpCodes.RESIZE_NEAREST_NEIGHBOR: BuiltinOptions.ResizeNearestNeighborOptions,
    BuiltinOpCodes.LEAKY_RELU: BuiltinOptions.LeakyReluOptions,
    BuiltinOpCodes.SQUARED_DIFFERENCE: BuiltinOptions.SquaredDifferenceOptions,
    BuiltinOpCodes.MIRROR_PAD: BuiltinOptions.MirrorPadOptions,
    BuiltinOpCodes.ABS: BuiltinOptions.AbsOptions,
    BuiltinOpCodes.SPLIT_V: BuiltinOptions.SplitVOptions,
    BuiltinOpCodes.UNIQUE: BuiltinOptions.UniqueOptions,
    BuiltinOpCodes.CEIL: BuiltinOptions.NONE,
    BuiltinOpCodes.REVERSE_V2: BuiltinOptions.ReverseV2Options,
    BuiltinOpCodes.ADD_N: BuiltinOptions.AddNOptions,
    BuiltinOpCodes.GATHER_ND: BuiltinOptions.GatherNdOptions,
    BuiltinOpCodes.COS: BuiltinOptions.CosOptions,
    BuiltinOpCodes.WHERE: BuiltinOptions.WhereOptions,
    BuiltinOpCodes.RANK: BuiltinOptions.RankOptions,
    BuiltinOpCodes.ELU: BuiltinOptions.NONE,
    BuiltinOpCodes.REVERSE_SEQUENCE: BuiltinOptions.ReverseSequenceOptions,
    BuiltinOpCodes.MATRIX_DIAG: BuiltinOptions.MatrixDiagOptions,
    BuiltinOpCodes.QUANTIZE: BuiltinOptions.QuantizeOptions,
    BuiltinOpCodes.MATRIX_SET_DIAG: BuiltinOptions.MatrixSetDiagOptions,
    BuiltinOpCodes.ROUND: BuiltinOptions.NONE,
    BuiltinOpCodes.HARD_SWISH: BuiltinOptions.HardSwishOptions,
    BuiltinOpCodes.IF: BuiltinOptions.IfOptions,
    BuiltinOpCodes.WHILE: BuiltinOptions.WhileOptions,
    BuiltinOpCodes.NON_MAX_SUPPRESSION_V4: BuiltinOptions.NonMaxSuppressionV4Options,
    BuiltinOpCodes.NON_MAX_SUPPRESSION_V5: BuiltinOptions.NonMaxSuppressionV5Options,
    BuiltinOpCodes.SCATTER_ND: BuiltinOptions.ScatterNdOptions,
    BuiltinOpCodes.SELECT_V2: BuiltinOptions.SelectV2Options,
    BuiltinOpCodes.DENSIFY: BuiltinOptions.DensifyOptions,
    BuiltinOpCodes.SEGMENT_SUM: BuiltinOptions.SegmentSumOptions,
    BuiltinOpCodes.BATCH_MATMUL: BuiltinOptions.BatchMatMulOptions,
}
BuiltinOptions.from_BuiltinOpCodes = lambda x: __BuiltinOptions_from_BuiltinOpCodes[x]
