# Copyright (c) 2019-2020, XMOS Ltd, All rights reserved

from enum import IntEnum

# TODO: consider adding fields to this enums for IDE support

class ActivationFunctionType(IntEnum): ...
class QuantizationDetails(IntEnum): ...
class FullyConnectedOptionsWeightsFormat(IntEnum): ...
class Padding(IntEnum): ...

